// generate pars.js: the exact optimal move count for every campaign level.
//
//   node tools/make-pars.mjs
//
// the campaign is frozen (levels.js header), so par is a fact, not a tunable:
// computed once here with a budget no phone should spend, shipped as a table,
// and verify-levels.mjs guards the table against ever drifting from the maths.
// dailies are not in this table on purpose: their space is infinite, so the
// phone computes theirs at board-open (proven <400ms across 3 years of dailies).
import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { levelBoard, LEVEL_COUNT } from '../src/lib/engine/levels.js'
import { optimal } from '../src/lib/engine/solver.js'

const OFFLINE_BUDGET = { maxNodes: 60_000_000 }

const pars = []
const started = Date.now()
for (let n = 1; n <= LEVEL_COUNT; n++) {
  const board = levelBoard(n)
  const result = optimal(board.tubes, board.params.capacity, OFFLINE_BUDGET)
  if (result.aborted) throw new Error(`level ${n}: optimal aborted even offline, raise the budget`)
  if (result.length > board.solution.length) throw new Error(`level ${n}: optimal beat by the proof solution, solver bug`)
  pars.push(result.length)
  if (n % 100 === 0) console.log(`${n}/${LEVEL_COUNT} (${((Date.now() - started) / 1000).toFixed(0)}s)`)
}

const body = `// GENERATED by tools/make-pars.mjs, do not edit: the exact optimal move
// count for campaign levels 1..${LEVEL_COUNT}, in order. frozen with the levels
// themselves; verify-levels.mjs spot-proves this table against the solver.
export const PARS = [
${Array.from({ length: Math.ceil(pars.length / 20) }, (_, row) => '  ' + pars.slice(row * 20, row * 20 + 20).join(', ') + ',').join('\n')}
]
`
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'engine', 'pars.js'), body)
console.log(`pars.js written: ${pars.length} levels, ${((Date.now() - started) / 1000).toFixed(0)}s`)
